# queen_file = open("queen.txt", "a")
# queen_file.write("Spike Edney - keyboards\n")
# queen_file.close()
'''
innuendo_file = open("queen_innuendo.txt", "w")
innuendo_file.write("1. Innuendo\n")
innuendo_file.write("2. I'm going slightly mad\n")
innuendo_file.write("3. Headlong\n")
innuendo_file.write("4. I can't live with you\n")
innuendo_file.write("5. Don't try so hard\n")
innuendo_file.write("6. All God's people\n")
innuendo_file.write("7. Ride the wild wind\n")
innuendo_file.write("8. These are the days of our lives\n")
innuendo_file.write("9. Delilah\n")
innuendo_file.write("10. Hitman\n")
innuendo_file.write("11. Bijou\n")
innuendo_file.write("12. The show must go on\n")
innuendo_file.close()
'''
innuendo_file = open("queen_innuendo.txt", "r")
print(innuendo_file.read())
innuendo_file.close()
